### ISSUE TITLE
example for splitting command line

### ISSUE THREAD

**Issue by rchikhi** [natir/yacrd#23]
What's the right way to obtain a splitted fasta?

I tried

` yacrd -i 35k_all_vs_all.paf -s yacrd.fa`

and it gives a few lines like:
`Chimeric        ERR1716491.27306        21246   152,0,152;187,2522,2709;13514,6541,20055;24,21222,21246
Chimeric        ERR1716491.58156        26998   2361,0,2361;2992,2680,5672;3227,6300,9527;3615,9919,13534;2457,16289,18746;5,26993,26998
...
`

and then crashes with

`thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', libcore/option.rs:345:21
note: Run with `RUST_BACKTRACE=1` for a backtrace.`

producing no fasta file. Dataset is https://transfer.sh/Renf8/35k_all_vs_all.paf in case you need it

**Comment by natir** [comment]
Hi,

I update the readme with example in this commit c80e581529ad14a545dc4c50c96f7fec68419ffc

I hope this can help you and other user.
