### ISSUE TITLE
trouble for installation

### ISSUE THREAD

**Issue by dcourtine** [natir/yacrd#24]
**EDIT**: False alarm, I forgot a parameter in the command. (`chimeric`).
It actually works very well.  It was just the Readme that confused me a little bit  :sweat_smile: .

--- 

Hi Pierre,

I'm very interested by your package, but the installation fails or almost fails. I tried to install from conda, source and cargo on my mac 10.14.4 and via Docker (official Rust image) for source and cargo. The two next commands outputs the same thing everytime:

- Get the help message

```bash
yacrd 0.5.1 Omanyte
Pierre Marijon <pierre.marijon@inria.fr>
Yet Another Chimeric Read Detector

USAGE:
    yacrd [SUBCOMMAND]

FLAGS:
    -h, --help       Prints help information
    -V, --version    Prints version information

SUBCOMMANDS:
    chimeric     In chimeric mode yacrd detect chimera if coverage gap are in middle of read
    help         Prints this message or the help of the given subcommand(s)
    scrubbing    In scrubbing mode yacrd remove all part of read not covered
```

- Run chimera detection

```
yacrd -i /data/mapping.paf -o /data/reads.yacrd
error: Found argument '-i' which wasn't expected, or isn't valid in this context

USAGE:
    yacrd [SUBCOMMAND]

For more information try --help
```

Do you have any idea of the origin of the problem?

Regards,

**Comment by natir** [comment]
Thank you for your bug report, I'm sorry for the confusion, I think I'm correcting the error that caused your confusion.
