### ISSUE TITLE
Provide clearer documentation on output file name munging (and/or a means to specify output file names)

### ISSUE THREAD

**Issue by oneillkza** [natir/yacrd#25]
Hi there,

I've just been testing out yacrd, with the following command:

```
$MINIMAP2 -x ava-ont -g 500 -t 72 $1.chopped.fastq.gz $1.chopped.fastq.gz | \
yacrd chimeric -f $1.chopped.fastq.gz > $1_dechimerized.fastq.gz 
```
ERR3219853.fastq.gz.chopped.fastq.gz
I ran it on a file named `ERR3219853.fastq.gz` (after also running PoreChop over that). 

What I expected, based on the readme, was for the fastq.gz to be written to `ERR3219853.fastq.gz_dechimerized.fastq.gz`. Instead, what I got was a text-based report written to `ERR3219853.fastq.gz_dechimerized.fastq.gz`, and the dechimerized fastq written to `ERR3219853_filtered.fastq.gz.chopped.fastq.gz.

Re-reading the readme, and digging into the source code, I now understand what it's getting at, but I think it would be better to more explicitly state how yacrd munges the output filename by inserting _filtered before the `"."`. Even better would be to provide an option to specify  the output filename (and report filename) explicitly.

**Comment by natir** [comment]
Hi oneillkza,

As I said in my answer to issue #26 I will try to improve the documentation and readme of yacrd and I also intend in future to modify the command line interface to make it easier to use yacrd.

Thanks again for your feedback.

**Comment by natir** [comment]
With version 0.6 beta solve this issue.

Extract, filter, split and scrubb of read are now subcommand and have an option to let user specify the output filename.
