### ISSUE TITLE
Please clarify whether chimeric read detection also performs scrubbing

### ISSUE THREAD

**Issue by oneillkza** [natir/yacrd#26]
Could you please clarify (and maybe also mention in the documentation): when running `yacrd chimeric`, does it also perform read scrubbing? 

I'd like to know whether I need to re-align the dechimerised reads -- ideally I'd like to not have to, as the all-to-all alignment is fairly expensive, even with minimap2.

**Comment by natir** [comment]
Hi oneillkza,

Sorry to notice that the readme is not clear enough. I will try to improve the documentation and in future change the command line interface.

To quickly answer your question subcommand chimeric in addition to chimeric reads detection can remove the regions with low coverage (which probably denotes chimeric reads) `--split` option, filtered `--filter` option or extract `--extract` option reads containing these type of regions. All these operations are not scrubbing which is performed by subcommand scrubbing.

If you run a chimeric detection with reads filtering like `yacrd chimeric -i ${paf} -f ${reads} -o ${yacrd_report}` you didn't need to rerun all-to-all alignment. If you use split option `--split` or scrubbing subcommand, sequence of 'chimeric' reads was modified and you need rerun mapping.

Thanks for your feedback I hope I answer to your question.

**Comment by oneillkza** [comment]
Thank you for the response, and for writing the tool!
