### ISSUE TITLE
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value'

### ISSUE THREAD

**Issue by vincentluo91** [natir/yacrd#28]
Hi, I installed yacrd and fpa  by conda, fpa worked but yacrd failed, it reported error like this: 
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:355:21
note: Run with `RUST_BACKTRACE=1` for a backtrace.
I tried on different machines but still, the same issue occurred . Could you please give any ideas about this? Thanks!

**Comment by natir** [comment]
Hi @vincentluo91,

Thank you for opening this issue

I'm sorry, I absolutely have to make the error messages of yacrd readable:).

Can you give me the command line you're trying to launch.

Are you sure all the input files exist and are not empty?

Thanks again !

**Comment by vincentluo91** [comment]
Thanks, @natir 
I double-checked the command that the input files are right and not empty, here is what I used:
yacrd --version
yacrd 0.5.1 Omanyte

minimap2 -t 24 -x ava-pb -g 800 test.fq test.fq >test.paf
yacrd scrubbing -c 4 -n 0.4 -m test.paf -s test.fq -S test.scrubbed.fq -r test.yacrd

Then, it returned errors mentioned above.

**Comment by natir** [comment]
Can you run these two commands and send me the result:

```
export RUST_BACKTRACE=full
yacrd scrubbing -c 4 -n 0.4 -m test.paf -s test.fq -S test.scrubbed.fq -r test.yacrd
```

**Comment by vincentluo91** [comment]
`$ yacrd scrubbing -c 4 -n 0.4 -m test.paf -s test.fq -S test.scrubbed.fq -r test.yacrd
`thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/libcore/option.rs:355:21
stack backtrace:
   0:     0x564e605c9943 - std::sys::unix::backtrace::tracing::imp::unwind_backtrace::h00d1e05a61bd440b
                               at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1:     0x564e605c42c8 - std::sys_common::backtrace::_print::hc0d53aca8da62f75
                               at src/libstd/sys_common/backtrace.rs:71
   2:     0x564e605c8a42 - std::panicking::default_hook::{{closure}}::h46d30bcc4bfff149
                               at src/libstd/sys_common/backtrace.rs:59
                               at src/libstd/panicking.rs:211
   3:     0x564e605c87ad - std::panicking::default_hook::h017696c2a8b7b16f
                               at src/libstd/panicking.rs:227
   4:     0x564e605c90f0 - std::panicking::rust_panic_with_hook::h8cbdfe43764887be
                               at src/libstd/panicking.rs:491
   5:     0x564e605c8c71 - std::panicking::continue_panic_fmt::h3d3c5a833c00a5e1
                               at src/libstd/panicking.rs:398
   6:     0x564e605c8b55 - rust_begin_unwind
                               at src/libstd/panicking.rs:325
   7:     0x564e605dccbc - core::panicking::panic_fmt::h4d67173bc68f6d5a
                               at src/libcore/panicking.rs:95
   8:     0x564e605dcbeb - core::panicking::panic::h6f50c0de2dcd7974
                               at src/libcore/panicking.rs:59
   9:     0x564e6053096d - yacrd::split::run::he0c3a69b12a35fb2
  10:     0x564e6052b486 - yacrd::main::he27cb460f24282cc
  11:     0x564e6053c252 - std::rt::lang_start::{{closure}}::h3791e91e32ff6beb
  12:     0x564e605c8af2 - std::panicking::try::do_call::h69790245ac2d03fe
                               at src/libstd/rt.rs:59
                               at src/libstd/panicking.rs:310
  13:     0x564e605d6df9 - __rust_maybe_catch_panic
                               at src/libpanic_unwind/lib.rs:102
  14:     0x564e605c94c3 - std::rt::lang_start_internal::h540c897fe52ba9c5
                               at src/libstd/panicking.rs:289
                               at src/libstd/panic.rs:398
                               at src/libstd/rt.rs:58
  15:     0x564e6052c7e1 - main
  16:     0x7fda491cb3d4 - __libc_start_main
  17:     0x564e6050a2cc - <unknown>
                               at ../sysdeps/x86_64/elf/start.S:103

**Comment by natir** [comment]
Ok sorry I found the trouble.

You need rename your file `test.fq` in `test.fastq`

yarcd support only sequence file with name like `anything.fasta` or `anything.fastq`

Tell me if it worked.

**Comment by vincentluo91** [comment]
It really works! Many thanks!
