### ISSUE TITLE
MDA chimeric reads

### ISSUE THREAD

**Issue by FSciammarella** [natir/yacrd#32]
Hey, @natir,

Any experience with using yacrd to clean MDA derived reads from wgaDNA?

**Comment by natir** [comment]
Hi @FSciammarella,

Sorry no, I never use this type of data.
But if you tell me where I can find information about this type of data (I have no idea what it is). Maybe I could see if yacrd can apply or not.

Best,
Pierre

**Comment by FSciammarella** [comment]
Hey, @natir,

MDA stands for Multiple Displacement Amplification, a technique to create exponentially many copies from low input ( one to a million cells) for library prep using principles of random priming and rolling circle amplification. 

Folks have been using it for Short Read Sequencing, with the caveat that it creates a fraction of chimeric strands. With short read sequencing that is no problem, as during lib prep, shearing and zise selection would isolate the chimeric junctions. But for long reads, there may be a great number of chimeric junctions being amplified, which, at least in my understanding, might cause problems in chimera identification through low coverage.

I myself don't have any data to point you to, as it seems very little explored in Long Read communities. But I have a great deal of interest as low input and MDA might help with a few personal projects of mine.

If I come across the data or generate it myself, I will keep you posted.

**Comment by natir** [comment]
> might cause problems in chimera identification through low coverage.
 yacrd is base on this idea.

But if I understand well how the MDA works, we generate large fragments that we will circularize and then sequence. Obviously, there will be a fraction of the reads that have been sequenced that will integrate the chimeric junction. Thes chimeric reads will have the same coverage rate as the non-chimeric reads of the fragment same.

But if we have more than one cells we can assume that the fragments were not created in the same position and therefore that there is still a drop in coverage of read contains chimeric junction. But I can't be sure.

I look forward to your first results on this dataset
