### ISSUE TITLE
Error: --input provided more than once....

### ISSUE THREAD

**Issue by nextgenusfs** [natir/yacrd#38]
I'm getting this error:
```
$ yacrd scrubb -i run1.all.report.yacrd -i run1.fastq -o run2.scrubbed.fastq
error: The argument '--input <input>' was provided more than once, but cannot be used multiple times

USAGE:
    yacrd --input <input> --output <output> scrubb --input <input> --output <output>

For more information try --help
```
Which seems odd that all the readme's show multiple inputs and outputs?  I don't recall seeing this behavior on centOS.  This is installed on Mac OS via bioconda. 
```
$ yacrd --version
yacrd 0.6.0
```

**Comment by natir** [comment]
Hi @nextgenusfs,

Thank you for using yacrd and creating this issue.

You have made a small error in the argument order. The -i run1.all.report.yacrd need to be before the subcommand scrubb.

The first part of the command line is for the general parameters, the part after subcommand is for this subcommand only.

The correct command line, to do what you want to do, is:

yacrd -i run1.all.report.yacrd -o /dev/null -i run1.fastq -o run2.scrubbed.fastq

Sorry for the -o /dev/null I need to found a way to fix this. I will try to clarify the parameter ordering in Readme.

**Comment by nextgenusfs** [comment]
Ok @natir thanks for clarification.  And thanks for `yacrd` its helping scrubb ONT reads prior to assembly!
