### ISSUE TITLE
Filter from .yacrd report

### ISSUE THREAD

**Issue by Maraikep** [natir/yacrd#40]
Dear Natir,
Thanks for the great tool for removing chimera from nanopore reads! Amazing!
The scrubb and filter commands work nicely for me using .paf as an input. However, I want to filter my reads now by the .yacrd report file. I am getting an error: "src/stack.rs 205". The command I was using is:
yacrd -i test.yacrd -o chimera/test.output.yacrd filter -i test.fastq -o chimera/test.fastq

Maybe I am doing something wrong? I would be very grateful if you could help me out.
Thanks a lot in advance for your kind support.
Best,
Maraike

**Comment by natir** [comment]
Hi @Maraikep, thank you for using yacrd and creating this issue.

I think your `.yacrd` file is corrupt or incomplete. 
Can you provide to me the `.yacrd` file (by email ?) or the last few lines.

Thanks again for your help.

**Comment by natir** [comment]
If you can use a devel version of yacrd the commit e86329e improve the error message, with more info on line where `yacrd` failled.

**Comment by natir** [comment]
@Maraikep if your trouble is solve could you please close this issue.

**Comment by Maraikep** [comment]
Dear Natir,
I am under the impression, the response function via email to github is not working properly. I am pasting a summary of my emails here, hoping this might solve the communication issue.

Again, thanks for your action and support! I highly appreciate.

Again, the error message was regarding the use of the report file instead of the .paf. You suspected the .yacrd file might be corrupt. I am having several samples, of course, the error message was the same for all of them. I am pasting the command  below and I am attaching the report file. Hopefully, this will help.

Thanks again and in advance for your support and patience.

Best,
Maraike

yacrd -i chimera/sn1_barcode01_600_1000_q10.fastq.yacrd -o test.report filter -i porechop/sn1_barcode01_600_1000_q10.fastq -o test.fastq


[nsmail-1-1.txt](https://github.com/natir/yacrd/files/4941861/nsmail-1-1.txt)

**Comment by natir** [comment]
Dear @Maraikep.

Strange bug with e-mail, but thank for the file. I understand and corrected my mistake. I didn't expect some read could be perfect and my yacrd report parser failed on this type of read.

Commits ab13fb6 solve this issue, I'm going to generate a new release with this bug fix.

**Comment by Maraikep** [comment]
Dear Natir,
Thanks for the prompt response and the information. I am happy that we managed to communicate! 
Thanks also for taking care of the issue in the next release. I am looking forward to it. Until now, I will simply repeat with the .paf (regenerating it again). 
Thanks again!
All the best!

**Comment by natir** [comment]
@Maraikep yacrd 0.6.2 with this bugfix is avaible in bioconda and crates.io

**Comment by Maraikep** [comment]
Great! Thanks a lot!
