### ISSUE TITLE
Faster yacrd

### ISSUE THREAD

**Issue by natir** [natir/yacrd#41]
Hi @jguhlin.

You seem to have some interesting ideas to improve yacrd runtime, (I stole one, by the way), can we discuss it somewhere?

Mail, twitter, this issue ?

Thanks for your intrest on yacrd.

**Comment by natir** [comment]
- [ ] Replace csv str parser by a Serde parser

**Comment by jguhlin** [comment]
Hey @natir ! Yeah, I've got a 10Gb genome with lots of nanopore I'd like to give this a go with, so I've been butchering the code (sorry!) lately. It's a 8.7Tb overlap PAF file (compressed, of course) from minimap2. 

Please e-mail me directly, joseph.guhlin@gmail.com

Cheers!
--Joseph

**Comment by Yutang-ETH** [comment]
Hi Joseph,

Thank you very much for developing such a nice tool. I am very interested in it and want to use it to detect chimeric reads in our ONT data set. I have around 77 gb ONT reads, which is around 30x coverage of my target genome (2.6 gb).

Now I am using minimap2 to do all-vs-all alignment as you suggested:
minimap2 -x ava-ont -g 500 reads.fasta reads.fasta > overlap.paf
However, I find that the paf file keeps increasing and it is 1.5 TB large now. We only have 4 TB disk memory left and I don't want our disk to crash, how could I solve this? Can I directly pipe paf to gzip to compress it? Does yacrd take gzip input?

Thank you very much.
Best wishes,
Yutang

**Comment by natir** [comment]
Hello,

First of all, could you avoid using someone else's issue to ask your question but create another issue. It's okay, but think about it next time.

As indicated in the [readme](https://github.com/natir/yacrd#compression) and in the yacrd help message, yacrd supports gzip, bzip and xz compression.

The option `-g 500` isn't recommend for [chimeric read](https://github.com/rrwick/Filtlong) detection it's recommend for [scrubbing](https://github.com/natir/yacrd#read-scrubbing-overlapping-recommended-parameter), which is a completely different task.

Given the size of your minimap2 output I think you should also consider filtering the output of minimap2, you can possibly remove small overlaps below 2000 for example, with [fpa](https://github.com/natir/fpa) I recommend this pipeline:

```
minimap2 -x ava-ont reads.fasta reads.fasta | fpa drop -l 2000 | xz -9 - > overlap.paf.xz
yacrd -i overlap.paf.xz -o reads.yacrd
```

I also recommend a first filter on your read with [Filtlong](https://github.com/rrwick/Filtlong) to remove short reads and reads with a small quality score.

If you have any other question don't hesitate to create another issue.

Cheers

**Comment by Yutang-ETH** [comment]
Hi,

Sorry, I will create a separate new issue next time.
I have done some quality check and filtering for my ONT long reads. I have 77 gb long reads over 20 kb after filtering so now I would like to know if there are some chimeric reads.

Thank you very much for the recommended pipeline, that's great. I will try that.

Best wishes,
Yutang
