### ISSUE TITLE
raw fastq file sequences ID did not fully appear in the *report.yacrd

### ISSUE THREAD

**Issue by jiajia19901101** [natir/yacrd#46]
Hi,
great tool, excited to get this to work! 
I want to use yacrd to detect chimeric reads in my pacbio ccs data. The data is amplified and the coverage is a little bit low. After running yacrd, I noticed the raw fastq file sequences ID did not fully appear in the *report.yacrd,  are there any reads that have been filtered and not labeled? If I just want to detect and  remove chimeric reads, can I just delete the reads labeled Chimeric?  What pipeline should I use? Could you please give me some suggestions?

This is the command I used:
minimap2 -x ava-pb  A.fastq.gz A.fastq.gz >A.overlap.paf
yacrd -i A.overlap.paf -o A.report.yacrd  split -i A.fastq.gz -o A.filter.fastq.gz

Thank you very much!

**Comment by natir** [comment]
Hi thanks. 

>I noticed the raw fastq file sequences ID did not fully appear in the *report.yacrd

I checked the code and thought about your problem. The only explanation I found is that the ID you did not find in the yacrd report is not present in the minimap output. Can you check this? Report generation is based only on paf file, so if read isn't present in paf it's logic yacrd didn't label it.

>  are there any reads that have been filtered and not labeled?

I check this read without label isn't filter or split, they are just write in output with out any modification.

If you just want remove reads with label Chimeric you can run this pipeline:

```
minimap2 -x ava-pb A.fastq.gz A.fastq.gz >A.overlap.paf
yacrd -i A.overlap.paf -o A.report.yacrd filter -i A.fastq.gz -o A.filter.fastq.gz
```

You can try to improve minimal coverage if you want `-c` option, but if you have a low coverage it's probably not a good idea.

**Comment by jiajia19901101** [comment]
Thanks you for your reply. You are right, the number of reads in report.yacrd are same with minimap2 output. I was wondering if you know why the output from minimap2 were not  reported all reads?

**Comment by natir** [comment]
I suppose some of your read haven't any mapping position with another read of your dataset. It's maybe because you have a low coverage, or because minimap2 parameter isn't the best for your dataset, maybe you can try `map-hifi` minimap2 preset or a mix between `map-hifi` and `ava-ont`

**Comment by jiajia19901101** [comment]
Thank you very much!

**Comment by Rohit-Satyam** [comment]
Hi @jiajia19901101 Did you observe the read ID missing from .yacrd report also missing from the fastq files? I haven't checked it but would like to know if you checked the same?
