### ISSUE TITLE
how about using -X when running minimap2?

### ISSUE THREAD

**Issue by jflot** [natir/yacrd#47]
Thanks for this nice tool!
Since it starts with an all-vs-all comparison, is it OK to use the parameter -X in minimap2 ("skip self and dual mappings (for the all-vs-all mode)") to save time and disk space?

**Comment by natir** [comment]
Hello thanks to use my ,

It's a good question, to be honest I didn't have answer and I probably can't produce one until 2 weeks or more.

If you can make a comparison before me, I will be happy to this information in Readme.
