### ISSUE TITLE
Why the overlap?

### ISSUE THREAD

**Issue by emiliomastriani** [natir/yacrd#49]
Dear all,
I successfully used yacrd after the minimap2 execution. It worked perfectly. I have the following doubt: why do we need to use the overlap step using minimap2. I refer to the instructions reported below (from the yacrd website):

1. minimap2 -x ava-ont my_reads.fq my_reads.fq > overlap.paf 
2. yacrd -i overlap.paf -o reads.yacrd extract -i my_reads.fastq -o reads.extract.fastq

Here is again my question: why at step 1 do we have to perform the overlap task? Which information will give us back used to identify the chimeric reads? 

Probably I miss some information.

Thank you very much for your support.

Dr. Mastriani Emilio

**Comment by natir** [comment]
Hi,

To identify chimeric reads yacrd analyse coverage of each reads, yacrd use overlap found by minimap2 as proxy of coverage of each reads. It's why we need step 1.

I hope I help and if you have other question please ask.

**Comment by natir** [comment]
@emiliomastriani if I answer your question please close this issue.
