### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by gwaldbieser** [natir/yacrd#5]
HI. I'm trying to install yacrd on CentOS 7.4.1708 with cmake v2.8.12.2 and GNU make v3..82

$ git clone https://github.com/natir/yacrd.git
Cloning into 'yacrd'...
remote: Counting objects: 129, done.
remote: Compressing objects: 100% (82/82), done.
remote: Total 129 (delta 70), reused 93 (delta 42), pack-reused 0
Receiving objects: 100% (129/129), 31.66 KiB | 0 bytes/s, done.
Resolving deltas: 100% (70/70), done.
$ cd yacrd
$ ls -l
total 12
-rw-r--r--. 1 root root  548 Mar 29 16:15 CMakeLists.txt
drwxr-xr-x. 2 root root   34 Mar 29 16:15 image
drwxr-xr-x. 2 root root   97 Mar 29 16:15 inc
-rw-r--r--. 1 root root 1071 Mar 29 16:15 LICENSE
-rw-r--r--. 1 root root 2480 Mar 29 16:15 Readme.md
drwxr-xr-x. 2 root root  117 Mar 29 16:15 src
drwxr-xr-x. 2 root root   28 Mar 29 16:15 test
$ mkdir build
$ cd build
$ cmake ..
-- The C compiler identification is GNU 4.8.5
-- The CXX compiler identification is GNU 4.8.5
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Configuring done
-- Generating done
-- Build files have been written to: /home/software/yacrd/build
$ make
Scanning dependencies of target yacrd
[ 20%] Building CXX object CMakeFiles/yacrd.dir/src/analysis.cpp.o
c++: error: unrecognized command line option â-Wodrâ
c++: error: unrecognized command line option â-std=c++14â
make[2]: *** [CMakeFiles/yacrd.dir/src/analysis.cpp.o] Error 1
make[1]: *** [CMakeFiles/yacrd.dir/all] Error 2
make: *** [all] Error 2
$ ls -l
total 28
-rw-r--r--. 1 root root 12003 Mar 29 16:16 CMakeCache.txt
drwxr-xr-x. 6 root root  4096 Mar 29 16:26 CMakeFiles
-rw-r--r--. 1 root root  1582 Mar 29 16:16 cmake_install.cmake
-rw-r--r--. 1 root root  7669 Mar 29 16:16 Makefile

**Comment by mahesh-panchal** [comment]
Hi,

The issue looks like you need a more up to date C compiler.
gcc-6.x + should be c++14 compliant.

(This problem looks familiar to me so I thought I'd help the author here).
Regards,
Mahesh.

**Comment by natir** [comment]
@gwaldbieser thanks to your issue
@mahesh-panchal thanks for your help.

I think it's trouble with gcc version, I just test yacrd with gcc >= 6.3. 
In fact this two flag isn't useful, I removed it in commit bf012ed5e7ea6f939fecf09863369d359b513e31

I hope this help you.
Actually I install a virtual machine to spot some other trouble with old gcc version.

**Comment by natir** [comment]
Ok after some test with some [docker image](https://github.com/Nercury/cmake-cpp-docker) you need gcc 5.2.1 to build and use yacrd.

I can build yarcd with gcc-4.7 but I have a runtime error, probably a conflict between some libstdc++ installed in docker image.

So maybe the actual version (f11a65db9197a89688b423bb7336b22cd2da37c0) of yarcd can be build and work on CentOS 7.4.

If it's true please close the issue.

**Comment by gwaldbieser** [comment]
Updating gcc worked. Thanks.
