### ISSUE TITLE
Error while running yacrd

### ISSUE THREAD

**Issue by SFreddi** [natir/yacrd#51]
Hi there,

I have been running the spaghetti.sh script for my Nanopore sequencing data. All samples work fine except for one which produces this error: 

**Error: Error in compression detection of file barcode41_set2_comb-porechop-nanofilt.paf

Caused by:
    File is too short, less than five bytes**

The file doesn't seem to have any issues (similar size and data as the other ones).

Any suggestions?

**Comment by natir** [comment]
Hello thank for use yacrd,

First are you sure `barcode41_set2_comb-porechop-nanofilt.paf` isn't empty ?

If it's not empty can you send me start (first 100 line) of file `barcode41_set2_comb-porechop-nanofilt.paf`. It's seems an upstream bug but I'm also maintainer of the upstream project.

**Comment by SFreddi** [comment]
Hi Natir, got it sorted! It was creating a large (180 GB) temporary file which my laptop couldn't handle, therefore killing the process. I used a more powerful computer and it worked. Still weird that it worked fine for all the other samples except for that single one!

Thanks for your help:)

**Comment by natir** [comment]
Hello,

In some cases, high error rate, repeated element or low complexity region, minimap2 generates a very large number of overlaps.

I will contact the authors of Spaghetti to see how we can detect and manage this problem.

**Comment by Luponsky** [comment]
Hello @natir I have exactly the same above mentioned problem, however my pc should be powerful enough to carryout the analysis. Do you have any suggestion?

**Comment by natir** [comment]
@Luponsky please create another issue:
- with version of yacrd use
- information about your system (os version etc)
- how you install yacrd 
- command line used (yacrd and minimap2 command)
- size of paf file output by minimap2

**Comment by Luponsky** [comment]
@natir I think the problem was related to minimap2 not yacrd... 
Thanks,
L
