### ISSUE TITLE
many metagenomic samples has redundant reads but not errors

### ISSUE THREAD

**Issue by jianshu93** [natir/yacrd#55]
Hello Team,

I understand this is for human genome like sequencing, one cell type, but for diverse samples like microbes in environmental samples, there are always many reads that appear only once, not because they are error but because they are only sequenced once, according to the Lander-waterman expectation, we need 10T to coverage all those bacterial genomes, which is not possible in the real world. 

Is this software useful in those cases? I can imagine the running time is related to O(N^2) since with minimap2 we have all VS. all comparisons, there are always several millions of reads, or sometimes billion of reads for real world environmental metagenome.

Thanks,

Jianshu

**Comment by natir** [comment]
Hello,

If we only want to remove chimeric reads, the fact that a read is only present once is not a problem. We can filter (or cut) only the chimeric reads and keep the uncovered reads.

On the other hand, if you're looking for scrubbing, it seems to me that this isn't the right tool for this type of dataset. Afterwards, you might consider reintroducing the uncovered reads after scrubbing.

Concerning calculation times. Minimap mapping time is obviously incompressible, but what worries me more is memory usage. One solution might be to segment the dataset. It's not ideal, and you risk losing precision and recall marignally, but it could work.

**Comment by jianshu93** [comment]
Thanks for the response! this is clear now. We may need to use some MinHash or X-drop like ones to remove those alignment that are not useful at all (too divergent sequences).

Jianshu

**Comment by natir** [comment]
If you want to filter overlaps you may be interested in https://github.com/natir/fpa

About minimap2 runtime yacrd not need full mapping only seed mapping.
